alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
more_used_cache = 1500
medium_used_cache = 800
less_used_cache = 50
char_cache = {
    'A': more_used_cache,
    'B': more_used_cache,
    'C': more_used_cache,
    'D': more_used_cache,
    'E': more_used_cache,
    'F': more_used_cache,
    'G': more_used_cache,
    'H': medium_used_cache,
    'I': medium_used_cache,
    'J': medium_used_cache,
    'K': less_used_cache,
    'L': medium_used_cache,
    'M': more_used_cache,
    'N': more_used_cache,
    'O': more_used_cache,
    'P': more_used_cache,
    'Q': medium_used_cache,
    'R': more_used_cache,
    'S': more_used_cache,
    'T': more_used_cache,
    'U': medium_used_cache,
    'V': medium_used_cache,
    'W': less_used_cache,
    'X': less_used_cache,
    'Y': less_used_cache,
    'Z': less_used_cache
}

char_map_position = {
    'A': 0,
    'Á': 0,
    'À': 0,
    'Ã': 0,
    'Â': 0,
    'B': 1,
    'C': 2,
    'D': 3,
    'E': 4,
    'É': 4,
    'Ê': 4,
    'F': 5,
    'G': 6,
    'H': 7,
    'I': 8,
    'J': 9,
    'K': 10,
    'L': 11,
    'M': 12,
    'N': 13,
    'O': 14,
    'Ó': 14,
    'Ô': 14,
    'Õ': 14,
    'P': 15,
    'Q': 16,
    'R': 17,
    'S': 18,
    'T': 19,
    'U': 20,
    'Ú': 20,
    'V': 21,
    'W': 22,
    'X': 23,
    'Y': 24,
    'Z': 25
}

mapping_letter = {
    '-': '-',
    'a': 'a',
    'à': 'a',
    'ã': 'a',
    'á': 'a',
    'â': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'é': 'e',
    'ê': 'e',
    'è': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'í': 'i',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'ô': 'o',
    'õ': 'o',
    'ó': 'o',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'ú': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z'
}